# =============================================================================
# sync_lollipop_geometry.py
# =============================================================================
# Recomputes the midpoint lollipop/socket symbol placement for Draw.io files
# that were previously generated by interface_diagram.py and then manually
# rearranged in Draw.io.
#
# The script scans for lollipop-mode edges and updates the attached midpoint
# symbols so their position and socket rotation match the current slope of the
# edge between the connected boxes.
#
# The script assumes the symbols are stored as edge-child vertices:
#   - lollipop circle: ellipse vertex under the edge
#   - socket bowl:     arc vertex under the edge
#
# -----------------------------------------------------------------------------
# Usage
# -----------------------------------------------------------------------------
#   py sync_lollipop_geometry.py [OPTIONS]
#
# Options:
#   --input    PATH    Input .drawio file to read
#   --output   PATH    Output .drawio file to write
#   --in-place         Update the input file in place
#
# Examples:
#   # Write a corrected copy
#   py sync_lollipop_geometry.py --input example_focus_SWC_B.drawio --output example_focus_SWC_B_fixed.drawio
#
#   # Update the file in place after manual rearrangement in Draw.io
#   py sync_lollipop_geometry.py --input example_focus_SWC_B.drawio --in-place
#
# =============================================================================

from __future__ import annotations

import argparse
import math
import xml.dom.minidom
import xml.etree.ElementTree as ET
from pathlib import Path


LOLLIPOP_DIAMETER = 12.0
SOCKET_DIAMETER = 16.0
SYMBOL_SEPARATION = 4.0


def parse_style(style: str) -> dict[str, str]:
	"""Parse a Draw.io style string into a dict."""
	result: dict[str, str] = {}
	for part in style.split(";"):
		if not part:
			continue
		if "=" in part:
			key, value = part.split("=", 1)
			result[key] = value
		else:
			result[part] = ""
	return result


def style_to_string(style_map: dict[str, str]) -> str:
	"""Serialize a style dict back to Draw.io style format."""
	parts: list[str] = []
	for key, value in style_map.items():
		parts.append(f"{key}={value}" if value else key)
	return ";".join(parts) + ";"


def get_geometry(cell: ET.Element) -> ET.Element | None:
	"""Return the mxGeometry child if present."""
	for child in cell:
		if child.tag == "mxGeometry":
			return child
	return None


def get_rect(cell: ET.Element) -> tuple[float, float, float, float] | None:
	"""Extract (x, y, w, h) from a vertex cell geometry."""
	geom = get_geometry(cell)
	if geom is None:
		return None
	return (
		float(geom.get("x", "0")),
		float(geom.get("y", "0")),
		float(geom.get("width", "0")),
		float(geom.get("height", "0")),
	)


def rel_point(rect: tuple[float, float, float, float], rel_xy: tuple[float, float]) -> tuple[float, float]:
	"""Convert a relative anchor point into absolute coordinates."""
	x, y, w, h = rect
	return x + rel_xy[0] * w, y + rel_xy[1] * h


def edge_anchor_points(edge: ET.Element, id_map: dict[str, ET.Element]) -> tuple[tuple[float, float], tuple[float, float]] | None:
	"""Compute the absolute source and target anchor points of an edge."""
	source_id = edge.get("source")
	target_id = edge.get("target")
	if not source_id or not target_id:
		return None
	source_cell = id_map.get(source_id)
	target_cell = id_map.get(target_id)
	if source_cell is None or target_cell is None:
		return None
	source_rect = get_rect(source_cell)
	target_rect = get_rect(target_cell)
	if source_rect is None or target_rect is None:
		return None

	style = parse_style(edge.get("style", ""))
	exit_xy = (float(style.get("exitX", "0.5")), float(style.get("exitY", "0.5")))
	entry_xy = (float(style.get("entryX", "0.5")), float(style.get("entryY", "0.5")))
	return rel_point(source_rect, exit_xy), rel_point(target_rect, entry_xy)


def set_edge_child_geometry(cell: ET.Element, offset_x: float, offset_y: float, width: float, height: float) -> None:
	"""Update an edge-child symbol geometry anchored at the edge midpoint."""
	geom = get_geometry(cell)
	if geom is None:
		geom = ET.SubElement(
			cell,
			"mxGeometry",
			{"x": "0.5", "y": "0", "width": str(width), "height": str(height), "relative": "1", "as": "geometry"},
		)
	else:
		geom.set("x", "0.500")
		geom.set("y", "0")
		geom.set("width", f"{width:.2f}")
		geom.set("height", f"{height:.2f}")
		geom.set("relative", "1")
		geom.set("as", "geometry")

	offset = None
	for child in geom:
		if child.tag == "mxPoint" and child.get("as") == "offset":
			offset = child
			break
	if offset is None:
		offset = ET.SubElement(geom, "mxPoint", {"as": "offset"})
	offset.set("x", f"{offset_x:.2f}")
	offset.set("y", f"{offset_y:.2f}")


def update_rotation(style: str, rotation_deg: float) -> str:
	"""Set the arc rotation in a Draw.io style string."""
	style_map = parse_style(style)
	style_map["rotation"] = f"{rotation_deg % 360.0:.1f}"
	return style_to_string(style_map)


def update_lollipop_symbols(edge: ET.Element, children: list[ET.Element], id_map: dict[str, ET.Element]) -> bool:
	"""Update one edge's lollipop midpoint symbols from the current edge slope."""
	anchors = edge_anchor_points(edge, id_map)
	if anchors is None:
		return False
	src_pt, tgt_pt = anchors
	angle_deg = math.degrees(math.atan2(tgt_pt[1] - src_pt[1], tgt_pt[0] - src_pt[0]))
	radians = math.radians(angle_deg)
	ux = math.cos(radians)
	uy = math.sin(radians)

	lp_center = (-SYMBOL_SEPARATION * ux, -SYMBOL_SEPARATION * uy)
	sock_center = (SYMBOL_SEPARATION * ux, SYMBOL_SEPARATION * uy)
	lp_left = lp_center[0] - LOLLIPOP_DIAMETER / 2.0
	lp_top = lp_center[1] - LOLLIPOP_DIAMETER / 2.0
	sock_left = sock_center[0] - SOCKET_DIAMETER / 2.0
	sock_top = sock_center[1] - SOCKET_DIAMETER / 2.0
	sock_rot = angle_deg + 270.0

	ellipse = None
	arc = None
	for child in children:
		style = child.get("style", "")
		if "ellipse;aspect=fixed" in style:
			ellipse = child
		elif "shape=mxgraph.basic.arc" in style:
			arc = child

	if ellipse is None or arc is None:
		return False

	set_edge_child_geometry(ellipse, lp_left, lp_top, LOLLIPOP_DIAMETER, LOLLIPOP_DIAMETER)
	set_edge_child_geometry(arc, sock_left, sock_top, SOCKET_DIAMETER, SOCKET_DIAMETER)
	arc.set("style", update_rotation(arc.get("style", ""), sock_rot))
	return True


def pretty_xml(element: ET.Element) -> str:
	"""Pretty-print XML with stable indentation."""
	raw_xml = ET.tostring(element, encoding="unicode")
	return xml.dom.minidom.parseString(raw_xml).toprettyxml(indent="  ")


def process_drawio(input_path: Path, output_path: Path) -> int:
	"""Update all lollipop midpoint symbols in a Draw.io file."""
	tree = ET.parse(input_path)
	root = tree.getroot()
	cells = root.findall(".//mxCell")
	id_map = {cell.get("id"): cell for cell in cells if cell.get("id")}
	children_by_parent: dict[str, list[ET.Element]] = {}
	for cell in cells:
		parent = cell.get("parent")
		if parent:
			children_by_parent.setdefault(parent, []).append(cell)

	updated = 0
	for cell in cells:
		if cell.get("edge") != "1":
			continue
		child_cells = children_by_parent.get(cell.get("id", ""), [])
		if not child_cells:
			continue
		if update_lollipop_symbols(cell, child_cells, id_map):
			updated += 1

	output_path.write_text(pretty_xml(root), encoding="utf-8")
	return updated


def main() -> None:
	parser = argparse.ArgumentParser(description="Re-align midpoint lollipop/socket symbols in a Draw.io file.")
	parser.add_argument("--input", required=True, help="Input .drawio file path.")
	parser.add_argument("--output", default="", help="Output .drawio file path.")
	parser.add_argument("--in-place", action="store_true", help="Overwrite the input file.")
	args = parser.parse_args()

	input_path = Path(args.input)
	if args.in_place:
		output_path = input_path
	elif args.output:
		output_path = Path(args.output)
	else:
		output_path = input_path.with_name(f"{input_path.stem}_synced{input_path.suffix}")

	updated = process_drawio(input_path, output_path)
	print(f"Updated lollipop edges: {updated}")
	print(f"Wrote Draw.io file: {output_path}")


if __name__ == "__main__":
	main()